### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by inputsh** [aleksandar-todorovic/indicator-github#2]
Things I'm planning on doing before I create a PPA:
- [x] Fix `View on GitHub` option
- [x] Reduce the size of the icons
- [x] Make a better `About...` window (idea abandoned, see [future plans](https://github.com/aleksandar-todorovic/indicator-github#future-plans))
- [x] Make a settings window (idea abandoned, see [future plans](https://github.com/aleksandar-todorovic/indicator-github#future-plans))
- [x] Find a way to display the number of notifications (idea abandoned, see [future plans](https://github.com/aleksandar-todorovic/indicator-github#future-plans))
- [ ] Make sure that application terminates with Ctrl + C
- [x] Store the token file in `~/.github-token.txt`
- [x] Make a list of the notifications in the dropdown menu. (idea abandoned, it would be a pain in the ass to implement if the user follows a lot of repositories)
- [x] Maybe separate the notifications based on the repository in question? (idea abandoned, see [future plans](https://github.com/aleksandar-todorovic/indicator-github#future-plans))
- [x] Display a `notify-send` if there's a new notification
- [ ] Display `No Internet connection` if there's no Internet connection

**Comment by c0b41** [comment]
instead of the txt file must be env

```
Indicator_Github_Token  = xxxxxxxxx
```
